export const PARCELS_LIST_REQUEST = 'PARCELS_LIST_REQUEST'
export const PARCELS_LIST_SUCCESS = 'PARCELS_LIST_SUCCESS'
export const PARCELS_LIST_FAIL = 'PARCELS_LIST_FAIL'
export const PARCELS_LIST_RESET = 'PARCELS_LIST_RESET'


export const PARCEL_CREATE_REQUEST = 'PARCEL_CREATE_REQUEST'
export const PARCEL_CREATE_SUCCESS = 'PARCEL_CREATE_SUCCESS'
export const PARCEL_CREATE_FAIL = 'PARCEL_CREATE_FAIL'
export const PARCEL_CREATE_RESET = 'PARCEL_CREATE_RESET'


export const PARCEL_DELETE_REQUEST = 'PARCEL_DELETE_REQUEST'
export const PARCEL_DELETE_FAIL = 'PARCEL_DELETE_FAIL'
export const PARCEL_DELETE_SUCCESS = 'PARCEL_DELETE_REQUEST'
export const PARCEL_DELETE_RESET = 'PARCEL_DELETE_RESET'

export const PARCEL_DETAILS_REQUEST = 'PARCEL_DETAILS_REQUEST'
export const PARCEL_DETAILS_SUCCESS = 'PARCEL_DETAILS_SUCCESS'
export const PARCEL_DETAILS_FAIL = 'PARCEL_DETAILS_FAIL'
export const PARCEL_DETAILS_RESET = 'PARCEL_DETAIL_RESET'

export const PARCEL_EDIT_RESET = 'PARCEL_EDIT_RESET'
export const PARCEL_EDIT_REQUEST = 'PARCEL_EDIT_REQUEST'
export const PARCEL_EDIT_SUCCESS = 'PARCEL_EDIT_SUCCESS'
export const PARCEL_EDIT_FAIL = 'PARCEL_EDIT_FAIL'






