

export const SEARCH_TRACKING_REQUEST = 'SEARCH_TRACKING_REQUEST';
export const SEARCH_TRACKING_SUCCESS = 'SEARCH_TRACKING_SUCCESS';
export const SEARCH_TRACKING_FAIL = 'SEARCH_TRACKING_FAIL';
export const SEARCH_TRACKING_RESET = 'SEARCH_TRACKING_RESET';
